arquivo = open("C:/Users/daniel_balera/Documents/txt/GOT.txt","w")
arquivo.write('Escrevendo no arquivo\n')
arquivo.write('John Snow\n')
arquivo.write('Arya Stark\n')
arquivo.write('Sansa Stark\n')
arquivo.write('Bran Stark\n')
arquivo.close()
print('fim do programa')
